debian: add libsecp256k1-dev to Build-Depends
Launchpad build #32876424 failed at the bsh/brightlink module compile
step:

    brightlink.c:67:10: fatal error: secp256k1.h: No such file or directory

The macOS homebrew formula already has the equivalent dep (depends_on
"secp256k1"); this propagates the same fix to the debian package so
launchpad builders pick up libsecp256k1.h headers.

The runtime dep (libsecp256k1.so.x) is auto-discovered through
${shlibs:Depends} during dpkg-shlibdeps, so we only need the build-time
header/library.